--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-05 20:16:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 42034)
-- Name: teste; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA teste;


ALTER SCHEMA teste OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 24577)
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 24576)
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24585)
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 24584)
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 32769)
-- Name: space_agency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_agency (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    country_code character varying(100) NOT NULL,
    abbrev character varying(50) NOT NULL,
    description text NOT NULL,
    administrator character varying(255),
    founding_year character varying(4),
    info_url character varying(200) NOT NULL,
    wiki_url character varying(200) NOT NULL,
    logo_url character varying(200),
    image_url character varying(200)
);


ALTER TABLE public.space_agency OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 32768)
-- Name: articles_agency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 32865)
-- Name: space_launch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_launch (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    last_updated timestamp with time zone NOT NULL,
    net timestamp with time zone NOT NULL,
    window_end timestamp with time zone NOT NULL,
    window_start timestamp with time zone NOT NULL,
    webcast_live boolean NOT NULL,
    image character varying(200),
    infographic character varying(200),
    launch_service_provider_id bigint NOT NULL,
    mission_id bigint NOT NULL,
    net_precision_id bigint NOT NULL,
    pad_id bigint NOT NULL,
    rocket_id bigint NOT NULL,
    status_id bigint NOT NULL,
    launch_id character varying(255),
    url character varying(255)
);


ALTER TABLE public.space_launch OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 32864)
-- Name: articles_launch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_launch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_launch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 32875)
-- Name: space_launch_programs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_launch_programs (
    id bigint NOT NULL,
    launch_id bigint NOT NULL,
    program_id bigint NOT NULL
);


ALTER TABLE public.space_launch_programs OWNER TO postgres;

--
-- TOC entry 279 (class 1259 OID 32874)
-- Name: articles_launch_programs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_launch_programs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_launch_programs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 32777)
-- Name: space_launchserviceprovider; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_launchserviceprovider (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    url character varying(200) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_launchserviceprovider OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 32776)
-- Name: articles_launchserviceprovider_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_launchserviceprovider ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_launchserviceprovider_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 32785)
-- Name: space_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_location (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    country_code character varying(10) NOT NULL,
    map_image character varying(200) NOT NULL,
    timezone_name character varying(50) NOT NULL,
    total_launch_count integer NOT NULL,
    total_landing_count integer NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_location OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 32784)
-- Name: articles_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 32831)
-- Name: space_mission_agencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_mission_agencies (
    id bigint NOT NULL,
    mission_id bigint NOT NULL,
    agency_id bigint NOT NULL
);


ALTER TABLE public.space_mission_agencies OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 32830)
-- Name: articles_mission_agencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_mission_agencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_mission_agencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 266 (class 1259 OID 32823)
-- Name: space_mission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_mission (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    type character varying(50) NOT NULL,
    orbit_id bigint NOT NULL
);


ALTER TABLE public.space_mission OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 32822)
-- Name: articles_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_mission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 32793)
-- Name: space_netprecision; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_netprecision (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    abbrev character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_netprecision OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 32792)
-- Name: articles_netprecision_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_netprecision ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_netprecision_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 260 (class 1259 OID 32801)
-- Name: space_orbit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_orbit (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    abbrev character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_orbit OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 32800)
-- Name: articles_orbit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_orbit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_orbit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 32837)
-- Name: space_pad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_pad (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    map_url character varying(200) NOT NULL,
    latitude character varying(50),
    longitude character varying(50),
    total_launch_count integer NOT NULL,
    location_id bigint NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_pad OWNER TO postgres;

--
-- TOC entry 269 (class 1259 OID 32836)
-- Name: articles_pad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_pad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_pad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 32853)
-- Name: space_program_agencies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_program_agencies (
    id bigint NOT NULL,
    program_id bigint NOT NULL,
    agency_id bigint NOT NULL
);


ALTER TABLE public.space_program_agencies OWNER TO postgres;

--
-- TOC entry 273 (class 1259 OID 32852)
-- Name: articles_program_agencies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_program_agencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_program_agencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 32845)
-- Name: space_program; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_program (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    description text NOT NULL,
    image_url character varying(200) NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    info_url character varying(200) NOT NULL,
    wiki_url character varying(200) NOT NULL,
    type character varying(50) NOT NULL
);


ALTER TABLE public.space_program OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 32844)
-- Name: articles_program_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_program ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 32859)
-- Name: space_rocket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_rocket (
    id bigint NOT NULL,
    configuration_id bigint NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_rocket OWNER TO postgres;

--
-- TOC entry 275 (class 1259 OID 32858)
-- Name: articles_rocket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_rocket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_rocket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 32807)
-- Name: space_rocketconfiguration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_rocketconfiguration (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    family character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    variant character varying(255) NOT NULL,
    url character varying(200) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_rocketconfiguration OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 32806)
-- Name: articles_rocketconfiguration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_rocketconfiguration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_rocketconfiguration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 264 (class 1259 OID 32815)
-- Name: space_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_status (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    abbrev character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.space_status OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 32814)
-- Name: articles_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16429)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16428)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16437)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16436)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16423)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16422)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16443)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16451)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16450)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16442)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16457)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16456)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16515)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16514)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 294 (class 1259 OID 41518)
-- Name: django_apscheduler_djangojob; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_apscheduler_djangojob (
    id character varying(255) NOT NULL,
    next_run_time timestamp with time zone,
    job_state bytea NOT NULL
);


ALTER TABLE public.django_apscheduler_djangojob OWNER TO postgres;

--
-- TOC entry 296 (class 1259 OID 41528)
-- Name: django_apscheduler_djangojobexecution; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_apscheduler_djangojobexecution (
    id bigint NOT NULL,
    status character varying(50) NOT NULL,
    run_time timestamp with time zone NOT NULL,
    duration numeric(15,2),
    finished numeric(15,2),
    exception character varying(1000),
    traceback text,
    job_id character varying(255) NOT NULL
);


ALTER TABLE public.django_apscheduler_djangojobexecution OWNER TO postgres;

--
-- TOC entry 295 (class 1259 OID 41527)
-- Name: django_apscheduler_djangojobexecution_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_apscheduler_djangojobexecution ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_apscheduler_djangojobexecution_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 293 (class 1259 OID 41496)
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- TOC entry 292 (class 1259 OID 41495)
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 41435)
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 41434)
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 286 (class 1259 OID 41441)
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- TOC entry 285 (class 1259 OID 41440)
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 41447)
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- TOC entry 287 (class 1259 OID 41446)
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 289 (class 1259 OID 41457)
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- TOC entry 291 (class 1259 OID 41476)
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- TOC entry 290 (class 1259 OID 41475)
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16415)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16414)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16407)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16406)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 16551)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 24614)
-- Name: django_site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 24613)
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 24623)
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 24622)
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 24631)
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 24630)
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 24637)
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 24636)
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 24643)
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 24642)
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 298 (class 1259 OID 41584)
-- Name: space_executionlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_executionlog (
    id bigint NOT NULL,
    script_name character varying(100) NOT NULL,
    last_executed timestamp with time zone NOT NULL,
    url character varying(200) NOT NULL
);


ALTER TABLE public.space_executionlog OWNER TO postgres;

--
-- TOC entry 297 (class 1259 OID 41583)
-- Name: space_executionlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_executionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.space_executionlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 33001)
-- Name: space_news; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.space_news (
    id bigint NOT NULL,
    title text NOT NULL,
    url text NOT NULL,
    image_url text NOT NULL,
    news_site text NOT NULL,
    summary text NOT NULL,
    published_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    featured boolean NOT NULL,
    launch_id bigint
);


ALTER TABLE public.space_news OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 33000)
-- Name: space_news_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.space_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.space_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16399)
-- Name: spaceexploration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.spaceexploration (
    id integer NOT NULL,
    source text,
    pmid text,
    doi text,
    title text,
    authorstring text,
    journaltitle text,
    pubyear text,
    journalissn text,
    pubtype text,
    isopenaccess text,
    inepmc text,
    inpmc text,
    haspdf text,
    hasbook text,
    hassuppl text,
    citedbycount text,
    hasreferences text,
    hastextminedterms text,
    hasdbcrossreferences text,
    haslabslinks text,
    hastmaccessionnumbers text,
    firstindexdate text,
    firstpublicationdate text,
    issue text,
    journalvolume text,
    pageinfo text,
    pmcid text,
    abstract text,
    affiliation text
);


ALTER TABLE public.spaceexploration OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16812)
-- Name: spaceexploration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.spaceexploration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.spaceexploration_id_seq OWNER TO postgres;

--
-- TOC entry 5284 (class 0 OID 0)
-- Dependencies: 236
-- Name: spaceexploration_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.spaceexploration_id_seq OWNED BY public.spaceexploration.id;


--
-- TOC entry 299 (class 1259 OID 42035)
-- Name: teste; Type: TABLE; Schema: teste; Owner: postgres
--

CREATE TABLE teste.teste (
);


ALTER TABLE teste.teste OWNER TO postgres;

--
-- TOC entry 300 (class 1259 OID 42038)
-- Name: teste2; Type: TABLE; Schema: teste; Owner: postgres
--

CREATE TABLE teste.teste2 (
    id integer NOT NULL,
    nome character varying
);


ALTER TABLE teste.teste2 OWNER TO postgres;

--
-- TOC entry 301 (class 1259 OID 42045)
-- Name: teste3; Type: TABLE; Schema: teste; Owner: postgres
--

CREATE TABLE teste.teste3 (
    id integer NOT NULL,
    id_teste2 integer,
    nome character varying
);


ALTER TABLE teste.teste3 OWNER TO postgres;

--
-- TOC entry 4908 (class 2604 OID 17062)
-- Name: spaceexploration id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spaceexploration ALTER COLUMN id SET DEFAULT nextval('public.spaceexploration_id_seq'::regclass);


--
-- TOC entry 4963 (class 2606 OID 24581)
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- TOC entry 4967 (class 2606 OID 24610)
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- TOC entry 4972 (class 2606 OID 24591)
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- TOC entry 4974 (class 2606 OID 24589)
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- TOC entry 5000 (class 2606 OID 32775)
-- Name: space_agency articles_agency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_agency
    ADD CONSTRAINT articles_agency_pkey PRIMARY KEY (id);


--
-- TOC entry 5041 (class 2606 OID 32871)
-- Name: space_launch articles_launch_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_pkey PRIMARY KEY (id);


--
-- TOC entry 5052 (class 2606 OID 32964)
-- Name: space_launch_programs articles_launch_programs_launch_id_program_id_0dd8a52e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch_programs
    ADD CONSTRAINT articles_launch_programs_launch_id_program_id_0dd8a52e_uniq UNIQUE (launch_id, program_id);


--
-- TOC entry 5054 (class 2606 OID 32879)
-- Name: space_launch_programs articles_launch_programs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch_programs
    ADD CONSTRAINT articles_launch_programs_pkey PRIMARY KEY (id);


--
-- TOC entry 5045 (class 2606 OID 32873)
-- Name: space_launch articles_launch_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_slug_key UNIQUE (slug);


--
-- TOC entry 5002 (class 2606 OID 32783)
-- Name: space_launchserviceprovider articles_launchserviceprovider_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launchserviceprovider
    ADD CONSTRAINT articles_launchserviceprovider_pkey PRIMARY KEY (id);


--
-- TOC entry 5004 (class 2606 OID 32791)
-- Name: space_location articles_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_location
    ADD CONSTRAINT articles_location_pkey PRIMARY KEY (id);


--
-- TOC entry 5019 (class 2606 OID 32887)
-- Name: space_mission_agencies articles_mission_agencies_mission_id_agency_id_827e6905_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission_agencies
    ADD CONSTRAINT articles_mission_agencies_mission_id_agency_id_827e6905_uniq UNIQUE (mission_id, agency_id);


--
-- TOC entry 5021 (class 2606 OID 32835)
-- Name: space_mission_agencies articles_mission_agencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission_agencies
    ADD CONSTRAINT articles_mission_agencies_pkey PRIMARY KEY (id);


--
-- TOC entry 5015 (class 2606 OID 32829)
-- Name: space_mission articles_mission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission
    ADD CONSTRAINT articles_mission_pkey PRIMARY KEY (id);


--
-- TOC entry 5006 (class 2606 OID 32799)
-- Name: space_netprecision articles_netprecision_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_netprecision
    ADD CONSTRAINT articles_netprecision_pkey PRIMARY KEY (id);


--
-- TOC entry 5008 (class 2606 OID 32805)
-- Name: space_orbit articles_orbit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_orbit
    ADD CONSTRAINT articles_orbit_pkey PRIMARY KEY (id);


--
-- TOC entry 5024 (class 2606 OID 32843)
-- Name: space_pad articles_pad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_pad
    ADD CONSTRAINT articles_pad_pkey PRIMARY KEY (id);


--
-- TOC entry 5029 (class 2606 OID 32857)
-- Name: space_program_agencies articles_program_agencies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_program_agencies
    ADD CONSTRAINT articles_program_agencies_pkey PRIMARY KEY (id);


--
-- TOC entry 5032 (class 2606 OID 32907)
-- Name: space_program_agencies articles_program_agencies_program_id_agency_id_01193656_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_program_agencies
    ADD CONSTRAINT articles_program_agencies_program_id_agency_id_01193656_uniq UNIQUE (program_id, agency_id);


--
-- TOC entry 5026 (class 2606 OID 32851)
-- Name: space_program articles_program_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_program
    ADD CONSTRAINT articles_program_pkey PRIMARY KEY (id);


--
-- TOC entry 5035 (class 2606 OID 32863)
-- Name: space_rocket articles_rocket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_rocket
    ADD CONSTRAINT articles_rocket_pkey PRIMARY KEY (id);


--
-- TOC entry 5010 (class 2606 OID 32813)
-- Name: space_rocketconfiguration articles_rocketconfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_rocketconfiguration
    ADD CONSTRAINT articles_rocketconfiguration_pkey PRIMARY KEY (id);


--
-- TOC entry 5012 (class 2606 OID 32821)
-- Name: space_status articles_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_status
    ADD CONSTRAINT articles_status_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 16549)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4933 (class 2606 OID 16472)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4936 (class 2606 OID 16441)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 16433)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 16463)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4925 (class 2606 OID 16427)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 16455)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4947 (class 2606 OID 16487)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4938 (class 2606 OID 16447)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 16461)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 16501)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4941 (class 2606 OID 16544)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4956 (class 2606 OID 16522)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5082 (class 2606 OID 41545)
-- Name: django_apscheduler_djangojob django_apscheduler_djangojob_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_apscheduler_djangojob
    ADD CONSTRAINT django_apscheduler_djangojob_pkey PRIMARY KEY (id);


--
-- TOC entry 5085 (class 2606 OID 41571)
-- Name: django_apscheduler_djangojobexecution django_apscheduler_djangojobexecution_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_pkey PRIMARY KEY (id);


--
-- TOC entry 5079 (class 2606 OID 41500)
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- TOC entry 5060 (class 2606 OID 41439)
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- TOC entry 5062 (class 2606 OID 41445)
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- TOC entry 5068 (class 2606 OID 41456)
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- TOC entry 5070 (class 2606 OID 41454)
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- TOC entry 5073 (class 2606 OID 41461)
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- TOC entry 5075 (class 2606 OID 41488)
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- TOC entry 5077 (class 2606 OID 41480)
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 16421)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4920 (class 2606 OID 16419)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4916 (class 2606 OID 16413)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 16557)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4977 (class 2606 OID 24620)
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- TOC entry 4979 (class 2606 OID 24618)
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 16814)
-- Name: spaceexploration publications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.spaceexploration
    ADD CONSTRAINT publications_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 24629)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- TOC entry 4983 (class 2606 OID 24691)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- TOC entry 4988 (class 2606 OID 24661)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- TOC entry 4986 (class 2606 OID 24635)
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- TOC entry 4990 (class 2606 OID 24641)
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- TOC entry 4996 (class 2606 OID 24651)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- TOC entry 4998 (class 2606 OID 24649)
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- TOC entry 5090 (class 2606 OID 41588)
-- Name: space_executionlog space_executionlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_executionlog
    ADD CONSTRAINT space_executionlog_pkey PRIMARY KEY (id);


--
-- TOC entry 5093 (class 2606 OID 42072)
-- Name: space_executionlog space_executionlog_url_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_executionlog
    ADD CONSTRAINT space_executionlog_url_key UNIQUE (url);


--
-- TOC entry 5049 (class 2606 OID 33168)
-- Name: space_launch space_launch_launch_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT space_launch_launch_id_key UNIQUE (launch_id);


--
-- TOC entry 5058 (class 2606 OID 33007)
-- Name: space_news space_news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_news
    ADD CONSTRAINT space_news_pkey PRIMARY KEY (id);


--
-- TOC entry 5088 (class 2606 OID 41582)
-- Name: django_apscheduler_djangojobexecution unique_job_executions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT unique_job_executions UNIQUE (job_id, run_time);


--
-- TOC entry 5095 (class 2606 OID 42044)
-- Name: teste2 teste2_pkey; Type: CONSTRAINT; Schema: teste; Owner: postgres
--

ALTER TABLE ONLY teste.teste2
    ADD CONSTRAINT teste2_pkey PRIMARY KEY (id);


--
-- TOC entry 5097 (class 2606 OID 42051)
-- Name: teste3 teste3_pkey; Type: CONSTRAINT; Schema: teste; Owner: postgres
--

ALTER TABLE ONLY teste.teste3
    ADD CONSTRAINT teste3_pkey PRIMARY KEY (id);


--
-- TOC entry 4964 (class 1259 OID 24612)
-- Name: account_emailaddress_upper; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_upper ON public.account_emailaddress USING btree (upper((email)::text));


--
-- TOC entry 4965 (class 1259 OID 24598)
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- TOC entry 4969 (class 1259 OID 24605)
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- TOC entry 4970 (class 1259 OID 24604)
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- TOC entry 5036 (class 1259 OID 32957)
-- Name: articles_launch_launch_service_provider_id_fefb1a17; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_launch_service_provider_id_fefb1a17 ON public.space_launch USING btree (launch_service_provider_id);


--
-- TOC entry 5037 (class 1259 OID 32958)
-- Name: articles_launch_mission_id_4f248e20; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_mission_id_4f248e20 ON public.space_launch USING btree (mission_id);


--
-- TOC entry 5038 (class 1259 OID 32959)
-- Name: articles_launch_net_precision_id_48292694; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_net_precision_id_48292694 ON public.space_launch USING btree (net_precision_id);


--
-- TOC entry 5039 (class 1259 OID 32960)
-- Name: articles_launch_pad_id_d78d87b7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_pad_id_d78d87b7 ON public.space_launch USING btree (pad_id);


--
-- TOC entry 5050 (class 1259 OID 32975)
-- Name: articles_launch_programs_launch_id_6927137b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_programs_launch_id_6927137b ON public.space_launch_programs USING btree (launch_id);


--
-- TOC entry 5055 (class 1259 OID 32976)
-- Name: articles_launch_programs_program_id_0c428f7c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_programs_program_id_0c428f7c ON public.space_launch_programs USING btree (program_id);


--
-- TOC entry 5042 (class 1259 OID 32961)
-- Name: articles_launch_rocket_id_469a3fa0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_rocket_id_469a3fa0 ON public.space_launch USING btree (rocket_id);


--
-- TOC entry 5043 (class 1259 OID 32956)
-- Name: articles_launch_slug_31ff6d93_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_slug_31ff6d93_like ON public.space_launch USING btree (slug varchar_pattern_ops);


--
-- TOC entry 5046 (class 1259 OID 32962)
-- Name: articles_launch_status_id_721e8b94; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_launch_status_id_721e8b94 ON public.space_launch USING btree (status_id);


--
-- TOC entry 5016 (class 1259 OID 32899)
-- Name: articles_mission_agencies_agency_id_cf3dec7a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_mission_agencies_agency_id_cf3dec7a ON public.space_mission_agencies USING btree (agency_id);


--
-- TOC entry 5017 (class 1259 OID 32898)
-- Name: articles_mission_agencies_mission_id_a388a454; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_mission_agencies_mission_id_a388a454 ON public.space_mission_agencies USING btree (mission_id);


--
-- TOC entry 5013 (class 1259 OID 32885)
-- Name: articles_mission_orbit_id_37206bc3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_mission_orbit_id_37206bc3 ON public.space_mission USING btree (orbit_id);


--
-- TOC entry 5022 (class 1259 OID 32905)
-- Name: articles_pad_location_id_c3295e11; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_pad_location_id_c3295e11 ON public.space_pad USING btree (location_id);


--
-- TOC entry 5027 (class 1259 OID 32919)
-- Name: articles_program_agencies_agency_id_34018656; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_program_agencies_agency_id_34018656 ON public.space_program_agencies USING btree (agency_id);


--
-- TOC entry 5030 (class 1259 OID 32918)
-- Name: articles_program_agencies_program_id_7f6c186f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_program_agencies_program_id_7f6c186f ON public.space_program_agencies USING btree (program_id);


--
-- TOC entry 5033 (class 1259 OID 32925)
-- Name: articles_rocket_configuration_id_f1d5f8d9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX articles_rocket_configuration_id_f1d5f8d9 ON public.space_rocket USING btree (configuration_id);


--
-- TOC entry 4926 (class 1259 OID 16550)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4931 (class 1259 OID 16483)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4934 (class 1259 OID 16484)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4921 (class 1259 OID 16469)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4942 (class 1259 OID 16499)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4945 (class 1259 OID 16498)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4948 (class 1259 OID 16513)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4951 (class 1259 OID 16512)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4939 (class 1259 OID 16545)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4954 (class 1259 OID 16533)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4957 (class 1259 OID 16534)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5080 (class 1259 OID 41536)
-- Name: django_apscheduler_djangojob_next_run_time_2f022619; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_apscheduler_djangojob_next_run_time_2f022619 ON public.django_apscheduler_djangojob USING btree (next_run_time);


--
-- TOC entry 5083 (class 1259 OID 41555)
-- Name: django_apscheduler_djangojobexecution_job_id_daf5090a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_apscheduler_djangojobexecution_job_id_daf5090a ON public.django_apscheduler_djangojobexecution USING btree (job_id);


--
-- TOC entry 5086 (class 1259 OID 41542)
-- Name: django_apscheduler_djangojobexecution_run_time_16edd96b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_apscheduler_djangojobexecution_run_time_16edd96b ON public.django_apscheduler_djangojobexecution USING btree (run_time);


--
-- TOC entry 5063 (class 1259 OID 41506)
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- TOC entry 5064 (class 1259 OID 41473)
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- TOC entry 5065 (class 1259 OID 41474)
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- TOC entry 5066 (class 1259 OID 41472)
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- TOC entry 5071 (class 1259 OID 41486)
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- TOC entry 4958 (class 1259 OID 16559)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4961 (class 1259 OID 16558)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4975 (class 1259 OID 24621)
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- TOC entry 4984 (class 1259 OID 24659)
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- TOC entry 4991 (class 1259 OID 24673)
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- TOC entry 4992 (class 1259 OID 24672)
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- TOC entry 4993 (class 1259 OID 24684)
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- TOC entry 4994 (class 1259 OID 24685)
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- TOC entry 5091 (class 1259 OID 42073)
-- Name: space_executionlog_url_a483b6cd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX space_executionlog_url_a483b6cd_like ON public.space_executionlog USING btree (url varchar_pattern_ops);


--
-- TOC entry 5047 (class 1259 OID 33169)
-- Name: space_launch_launch_id_0fdbf40b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX space_launch_launch_id_0fdbf40b_like ON public.space_launch USING btree (launch_id varchar_pattern_ops);


--
-- TOC entry 5056 (class 1259 OID 33013)
-- Name: space_news_launch_id_54f1824a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX space_news_launch_id_54f1824a ON public.space_news USING btree (launch_id);


--
-- TOC entry 4968 (class 1259 OID 24611)
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- TOC entry 5107 (class 2606 OID 24592)
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5108 (class 2606 OID 24599)
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5121 (class 2606 OID 32926)
-- Name: space_launch articles_launch_launch_service_provi_fefb1a17_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_launch_service_provi_fefb1a17_fk_articles_ FOREIGN KEY (launch_service_provider_id) REFERENCES public.space_launchserviceprovider(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5122 (class 2606 OID 32931)
-- Name: space_launch articles_launch_mission_id_4f248e20_fk_articles_mission_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_mission_id_4f248e20_fk_articles_mission_id FOREIGN KEY (mission_id) REFERENCES public.space_mission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5123 (class 2606 OID 32936)
-- Name: space_launch articles_launch_net_precision_id_48292694_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_net_precision_id_48292694_fk_articles_ FOREIGN KEY (net_precision_id) REFERENCES public.space_netprecision(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5127 (class 2606 OID 32965)
-- Name: space_launch_programs articles_launch_prog_launch_id_6927137b_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch_programs
    ADD CONSTRAINT articles_launch_prog_launch_id_6927137b_fk_articles_ FOREIGN KEY (launch_id) REFERENCES public.space_launch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5128 (class 2606 OID 32970)
-- Name: space_launch_programs articles_launch_prog_program_id_0c428f7c_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch_programs
    ADD CONSTRAINT articles_launch_prog_program_id_0c428f7c_fk_articles_ FOREIGN KEY (program_id) REFERENCES public.space_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5124 (class 2606 OID 32946)
-- Name: space_launch articles_launch_rocket_id_469a3fa0_fk_articles_rocket_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_rocket_id_469a3fa0_fk_articles_rocket_id FOREIGN KEY (rocket_id) REFERENCES public.space_rocket(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5125 (class 2606 OID 32951)
-- Name: space_launch articles_launch_status_id_721e8b94_fk_articles_status_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT articles_launch_status_id_721e8b94_fk_articles_status_id FOREIGN KEY (status_id) REFERENCES public.space_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5115 (class 2606 OID 32893)
-- Name: space_mission_agencies articles_mission_age_agency_id_cf3dec7a_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission_agencies
    ADD CONSTRAINT articles_mission_age_agency_id_cf3dec7a_fk_articles_ FOREIGN KEY (agency_id) REFERENCES public.space_agency(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5116 (class 2606 OID 32888)
-- Name: space_mission_agencies articles_mission_age_mission_id_a388a454_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission_agencies
    ADD CONSTRAINT articles_mission_age_mission_id_a388a454_fk_articles_ FOREIGN KEY (mission_id) REFERENCES public.space_mission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5114 (class 2606 OID 32880)
-- Name: space_mission articles_mission_orbit_id_37206bc3_fk_articles_orbit_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_mission
    ADD CONSTRAINT articles_mission_orbit_id_37206bc3_fk_articles_orbit_id FOREIGN KEY (orbit_id) REFERENCES public.space_orbit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5117 (class 2606 OID 32900)
-- Name: space_pad articles_pad_location_id_c3295e11_fk_articles_location_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_pad
    ADD CONSTRAINT articles_pad_location_id_c3295e11_fk_articles_location_id FOREIGN KEY (location_id) REFERENCES public.space_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5118 (class 2606 OID 32913)
-- Name: space_program_agencies articles_program_age_agency_id_34018656_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_program_agencies
    ADD CONSTRAINT articles_program_age_agency_id_34018656_fk_articles_ FOREIGN KEY (agency_id) REFERENCES public.space_agency(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5119 (class 2606 OID 32908)
-- Name: space_program_agencies articles_program_age_program_id_7f6c186f_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_program_agencies
    ADD CONSTRAINT articles_program_age_program_id_7f6c186f_fk_articles_ FOREIGN KEY (program_id) REFERENCES public.space_program(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5120 (class 2606 OID 32920)
-- Name: space_rocket articles_rocket_configuration_id_f1d5f8d9_fk_articles_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_rocket
    ADD CONSTRAINT articles_rocket_configuration_id_f1d5f8d9_fk_articles_ FOREIGN KEY (configuration_id) REFERENCES public.space_rocketconfiguration(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5099 (class 2606 OID 16478)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5100 (class 2606 OID 16473)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5098 (class 2606 OID 16464)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5101 (class 2606 OID 16493)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5102 (class 2606 OID 16488)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5103 (class 2606 OID 16507)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5104 (class 2606 OID 16502)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5105 (class 2606 OID 16523)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5106 (class 2606 OID 16528)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5134 (class 2606 OID 41564)
-- Name: django_apscheduler_djangojobexecution django_apscheduler_djangojobexecution_job_id_daf5090a_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_apscheduler_djangojobexecution
    ADD CONSTRAINT django_apscheduler_djangojobexecution_job_id_daf5090a_fk FOREIGN KEY (job_id) REFERENCES public.django_apscheduler_djangojob(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5130 (class 2606 OID 41501)
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5131 (class 2606 OID 41462)
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5132 (class 2606 OID 41467)
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5133 (class 2606 OID 41481)
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5112 (class 2606 OID 24674)
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5113 (class 2606 OID 24692)
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5110 (class 2606 OID 24667)
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5111 (class 2606 OID 24662)
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5109 (class 2606 OID 24654)
-- Name: socialaccount_socialaccount socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5126 (class 2606 OID 42092)
-- Name: space_launch space_launch_pad_id_679341df_fk_space_pad_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_launch
    ADD CONSTRAINT space_launch_pad_id_679341df_fk_space_pad_id FOREIGN KEY (pad_id) REFERENCES public.space_pad(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5129 (class 2606 OID 33008)
-- Name: space_news space_news_launch_id_54f1824a_fk_space_launch_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.space_news
    ADD CONSTRAINT space_news_launch_id_54f1824a_fk_space_launch_id FOREIGN KEY (launch_id) REFERENCES public.space_launch(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5135 (class 2606 OID 42052)
-- Name: teste3 t3t2; Type: FK CONSTRAINT; Schema: teste; Owner: postgres
--

ALTER TABLE ONLY teste.teste3
    ADD CONSTRAINT t3t2 FOREIGN KEY (id_teste2) REFERENCES teste.teste2(id) NOT VALID;


-- Completed on 2024-07-05 20:16:46

--
-- PostgreSQL database dump complete
--

