# Generated by Django 5.0.1 on 2024-08-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("pmid", models.CharField(blank=True, max_length=50, null=True)),
                ("pmcid", models.CharField(blank=True, max_length=50, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("author_full_name", models.TextField(blank=True, null=True)),
                ("journal_title", models.TextField(blank=True, null=True)),
                (
                    "journal_issn",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "journal_issue",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "journal_volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "journal_year_of_publication",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("abstract_text", models.TextField(blank=True, null=True)),
                (
                    "publication_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                ("pub_model", models.CharField(blank=True, max_length=50, null=True)),
                ("pub_type_list", models.TextField(blank=True, null=True)),
                ("grants_list", models.TextField(blank=True, null=True)),
                ("full_text_url_list", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "space_literature",
            },
        ),
    ]
