# Generated by Django 5.0.1 on 2024-08-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author_affiliation_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
