# Generated by Django 5.0.1 on 2024-06-01 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('administrator', models.CharField(blank=True, max_length=255, null=True)),
                ('founding_year', models.CharField(blank=True, max_length=4, null=True)),
                ('info_url', models.URLField(blank=True, default='')),
                ('wiki_url', models.URLField(blank=True, default='')),
                ('logo_url', models.URLField(blank=True, default='', null=True)),
                ('image_url', models.URLField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'space_agency',
            },
        ),
        migrations.CreateModel(
            name='LaunchServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_launchserviceprovider',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('map_image', models.URLField()),
                ('timezone_name', models.CharField(max_length=50)),
                ('total_launch_count', models.IntegerField()),
                ('total_landing_count', models.IntegerField()),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_location',
            },
        ),
        migrations.CreateModel(
            name='NetPrecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_netprecision',
            },
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_orbit',
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_rocket',
            },
        ),
        migrations.CreateModel(
            name='RocketConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('variant', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_rocketconfiguration',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbrev', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'space_status',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('type', models.CharField(max_length=50)),
                ('agencies', models.ManyToManyField(to='space.agency')),
                ('orbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.orbit')),
            ],
            options={
                'db_table': 'space_mission',
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('last_updated', models.DateTimeField()),
                ('net', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('window_start', models.DateTimeField()),
                ('webcast_live', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True, null=True)),
                ('infographic', models.URLField(blank=True, null=True)),
                ('launch_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.launchserviceprovider')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.mission')),
                ('net_precision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.netprecision')),
            ],
            options={
                'db_table': 'space_launch',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('news_site', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('featured', models.BooleanField()),
                ('launch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.launch')),
            ],
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('map_url', models.URLField()),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('total_launch_count', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.location')),
            ],
            options={
                'db_table': 'space_pad',
            },
        ),
        migrations.AddField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.pad'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('info_url', models.URLField(blank=True, default='')),
                ('wiki_url', models.URLField(blank=True)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('agencies', models.ManyToManyField(to='space.agency')),
            ],
            options={
                'db_table': 'space_program',
            },
        ),
        migrations.AddField(
            model_name='launch',
            name='programs',
            field=models.ManyToManyField(to='space.program'),
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.rocket'),
        ),
        migrations.AddField(
            model_name='rocket',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.rocketconfiguration'),
        ),
        migrations.AddField(
            model_name='launch',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.status'),
        ),
    ]
