# Generated by Django 5.0.1 on 2024-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
