# Generated by Django 5.0.1 on 2024-06-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_initial'),
    ]

    operations = [

    ]
