# Generated by Django 5.0.1 on 2024-08-18 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0002_alter_agency_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agency",
            name="featured",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="launcher_list",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="agency",
            name="spacecraft_list",
        ),
    ]
