# Generated by Django 5.0.1 on 2024-07-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_alter_news_news_site_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(),
        ),
    ]
