# Generated by Django 5.0.1 on 2024-07-29 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_news_image_url_alter_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pad',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pad',
            name='map_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pad',
            name='orbital_launch_attempt_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pad',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='wiki_url',
            field=models.URLField(blank=True, default='-'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='space.pad'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='wiki_url',
            field=models.URLField(blank=True, default='-'),
        ),
        migrations.CreateModel(
            name='InfoURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('feature_image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='space.launch')),
            ],
            options={
                'db_table': 'space_info_url',
            },
        ),
        migrations.CreateModel(
            name='VidURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('feature_image', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='space.launch')),
            ],
            options={
                'db_table': 'space_vid_url',
            },
        ),
    ]
