# Generated by Django 5.0.1 on 2024-06-01 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('news_site', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('featured', models.BooleanField()),
                ('launch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.launch')),
            ],
        ),
    ]
