# Generated by Django 5.0.1 on 2024-08-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_remove_agency_featured_remove_agency_launcher_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='launcher_list',
            field=models.ManyToManyField(related_name='launcher_agencies', to='space.launcherconfig'),
        ),
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='spacecraft_list',
            field=models.ManyToManyField(related_name='spacecraft_agencies', to='space.spacecraftconfig'),
        ),
    ]
