# Generated by Django 5.0.1 on 2024-08-17 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_astronautrole_astronautstatus_astronauttype_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='astronaut',
            table='space_astronaut',
        ),
        migrations.AlterModelTable(
            name='astronautrole',
            table='space_astronaut_role',
        ),
        migrations.AlterModelTable(
            name='astronauttype',
            table='space_astronaut_type',
        ),
        migrations.AlterModelTable(
            name='crew',
            table='space_crew',
        ),
        migrations.AlterModelTable(
            name='dockingevent',
            table='space_docking_event',
        ),
        migrations.AlterModelTable(
            name='dockinglocation',
            table='space_docking_location',
        ),
        migrations.AlterModelTable(
            name='expedition',
            table='space_expedition',
        ),
        migrations.AlterModelTable(
            name='spacecraftflight',
            table='space_spacecraft_flight',
        ),
        migrations.AlterModelTable(
            name='spacestation',
            table='space_spacestation',
        ),
        migrations.AlterModelTable(
            name='spacestationstatus',
            table='space_spacestation_status',
        ),
        migrations.AlterModelTable(
            name='spacewalk',
            table='space_spacewalk',
        ),
        migrations.AlterModelTable(
            name='timelineeventtype',
            table='space_timeline_event_type',
        ),
    ]
