# Generated by Django 5.0.1 on 2024-06-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launch_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='news',
            table='space_news',
        ),
    ]
