# Generated by Django 5.0.1 on 2024-08-20 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_agency_featured_agency_launcher_list_agency_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherconfig',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.program'),
        ),
    ]
