# Generated by Django 5.0.1 on 2024-06-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_launch_launch_id_alter_news_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
