# Generated by Django 5.0.1 on 2024-08-20 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_alter_launcherconfig_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.agency'),
        ),
    ]
