# Generated by Django 5.0.1 on 2024-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_alter_pad_agency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='net',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='webcast_live',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
