# Generated by Django 5.0.1 on 2024-07-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_launch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.CharField(max_length=100)),
                ('last_executed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
