# Generated by Django 5.0.1 on 2024-07-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_executionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionLog',
        ),
    ]
