# Generated by Django 5.0.1 on 2024-08-20 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_alter_launch_last_updated_alter_launch_net_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.mission'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='net_precision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.netprecision'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.pad'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.rocket'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.launchstatus'),
        ),
    ]
