# Generated by Django 5.0.1 on 2024-08-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0008_alter_launch_mission_alter_launch_net_precision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infourls',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.language'),
        ),
        migrations.AlterField(
            model_name='infourls',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infourls',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.infourltype'),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.language'),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.vidurltype'),
        ),
    ]
