# Generated by Django 5.0.1 on 2024-08-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_alter_infourls_language_alter_infourls_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcherconfig',
            name='program',
        ),
        migrations.AddField(
            model_name='launcherconfig',
            name='program',
            field=models.ManyToManyField(to='space.program'),
        ),
    ]
