# Generated by Django 5.0.1 on 2024-08-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0010_remove_launcherconfig_program_launcherconfig_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpatches',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.agency'),
        ),
        migrations.AlterField(
            model_name='missionpatches',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.program'),
        ),
    ]
