# Generated by Django 5.0.1 on 2024-08-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0011_alter_missionpatches_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='space.launch'),
        ),
    ]
