# Generated by Django 5.0.1 on 2024-08-20 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0012_alter_infourls_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.landinglocation'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.landingtype'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.agency'),
        ),
        migrations.AlterField(
            model_name='launcherstage',
            name='landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.landing'),
        ),
        migrations.AlterField(
            model_name='launcherstage',
            name='launcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.launcher'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='orbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.orbit'),
        ),
        migrations.AlterField(
            model_name='pad',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.location'),
        ),
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.programtype'),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.launcherconfig'),
        ),
        migrations.AlterField(
            model_name='spacecraftconfig',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.agency'),
        ),
        migrations.AlterField(
            model_name='spacecraftconfig',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.spacecrafttype'),
        ),
    ]
