# Generated by Django 5.0.1 on 2024-08-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0013_alter_landing_location_alter_landing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherconfig',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='space.agency'),
        ),
    ]
