# Generated by Django 5.0.1 on 2024-08-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0014_alter_launcherconfig_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='failreason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
