# Generated by Django 5.0.1 on 2024-08-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0015_alter_agency_featured_alter_launch_failreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='launcher_stage',
            field=models.ManyToManyField(blank=True, null=True, to='space.launcherstage'),
        ),
    ]
