# Generated by Django 5.0.1 on 2024-08-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0016_alter_agency_country_code_alter_agency_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rocket',
            name='launcher_stage',
            field=models.ManyToManyField(to='space.launcherstage'),
        ),
    ]
