# Generated by Django 5.0.1 on 2024-08-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0017_alter_rocket_launcher_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infourls',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rocket',
            name='launcher_stage',
            field=models.ManyToManyField(default=1, to='space.launcherstage'),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
