# Generated by Django 5.0.1 on 2024-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0017_alter_rocket_launcher_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rocket",
            name="launcher_stage",
            field=models.ManyToManyField(default=1, to="space.launcherstage"),
        ),
    ]
