# Generated by Django 5.0.1 on 2024-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0018_alter_infourls_title_alter_rocket_launcher_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
