# Generated by Django 5.0.1 on 2024-08-20 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("space", "0018_alter_rocket_launcher_stage"),
        ("space", "0019_alter_agency_featured"),
    ]

    operations = []
