# Generated by Django 5.0.1 on 2024-09-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0020_merge_20240820_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='abbrev',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='country_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
